[features]
seeds = false
skip-lint = false
[programs.localnet]
lottie = "5rrtDkohLqXvzrxfVTkHK685HztRd8Gzbx6yeNbuDiMk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/diegofigs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
oracle = "yarn run ts-node oracle.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[test]
startup_wait = 15000

[[test.validator.clone]] # sbv2 programID
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"

[[test.validator.clone]] # sbv2 IDL
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

[[test.validator.clone]] # sbv2 SbState
address = "CyZuD7RPDcrqCGbNvLCyqk6Py9cEZTKmNKujfPi3ynDd"

[[test.validator.clone]] # sbv2 attestation programID
address = "sbattyXrzedoNATfc4L31wC9Mhxsi1BmFhTiN8gDshx"

[[test.validator.clone]] # sbv2 idl devnet
address = "5ExuoQR69trmKQfB95fDsUGsUrrChbGq9PFgt8qouncz"

[[test.validator.clone]] # Metaplex programID
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 

[[test.validator.clone]] # Stake Pool programID
address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"

[[test.validator.clone]] # bSOL mint
address = "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1"

[[test.validator.clone]] # mSOL mint
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"

[[test.validator.clone]] # bSOL/SOL data feed
address = "2yWjZ439MMEtAZZxk4RC2C9GB71fHaWHYm82943CvNBy"

# SolBlaze mainnet
[[test.validator.clone]]
address = "stk9ApL5HeVAwPLr3TLhDXdZS8ptVu7zp6ov8HFDuMi" # Solblaze Pool
[[test.validator.clone]]
address = "rsrxDvYUXjH1RQj2Ke36LNZEVqGztATxFkqNukERqFT" # Solblaze Reserve
[[test.validator.clone]]
address = "1istpXjy8BM7Vd5vPfA485frrV7SRJhgq5vs3sskWmc" # Solblaze Validator List
# [[test.validator.clone]]
# address = "upd7dui9VYY9JbYLgpFy4rh9WAMjcm8YxiUBnENy69j" # Solblaze update
# [[test.validator.clone]]
# address = "b1azeTfpBiKN6AhEGVd1iPBsX3vmZqnFmS7Kqau7a2w" # Solblaze manager
# [[test.validator.clone]]
# address = "6WecYymEARvjG5ZyqkrVQ6YkhPfujNzWpSPwNKXHCbV2" # Solblaze stake authority
# [[test.validator.clone]]
# address = "Dpo148tVGewDPyh2FkGV18gouWctbdX2fHJopJGe9xv1" # Solblaze Fee depot
# [[test.validator.clone]]
# address = "Hn5e7ky1y7pGMbe8X5G51YcDyzo7GomZ1wUcS6HZEJkT" # Solblaze Validator Info

# SolBlaze devnet
# [[test.validator.clone]]
# address = "azFVdHtAJN8BX3sbGAYkXvtdjdrT5U6rj9rovvUFos9" # Solblaze Pool
# [[test.validator.clone]]
# address = "aRkys1kVHeysrcn9bJFat9FkvoyyYD8M1kK286X3Aro" # Solblaze Reserve
# [[test.validator.clone]]
# address = "aEP3DRe8ssFXDFokXiNMo4UXLhpL7LEPVbneUsfqeaJ" # Solblaze Validator List
# [[test.validator.clone]]
# address = "upd7dui9VYY9JbYLgpFy4rh9WAMjcm8YxiUBnENy69j" # Solblaze update
# [[test.validator.clone]]
# address = "b1azeTfpBiKN6AhEGVd1iPBsX3vmZqnFmS7Kqau7a2w" # Solblaze manager
# [[test.validator.clone]]
# address = "4vJJQTSApqig3DEZbLRNuWscQfE6GVisSgRPraiPn1Fz" # Solblaze stake authority
# [[test.validator.clone]]
# address = "Dpo148tVGewDPyh2FkGV18gouWctbdX2fHJopJGe9xv1" # Solblaze Fee depot
# [[test.validator.clone]]
# address = "Hn5e7ky1y7pGMbe8X5G51YcDyzo7GomZ1wUcS6HZEJkT" # Solblaze Validator Info

# [[test.validator.clone]]
# address = "CLoCKyJ6DXBJqqu2VWx9RLbgnwwR6BMHHuyasVmfMzBh" # clockwork program
# address = "3XXuUFfweXBwFgFfYaejLvZE4cGZiHgKiGfMtdxNzYmv" # clockwork v1 program
