name: Anchor Test

on:
  push:
     branches: [ main, develop ]
  pull_request:
     branches: [ main ]

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # from https://github.com/ochaloup/projectserum-build-docker
    container: docker.io/ochaloup/projectserum-build:v0.28.0_sol1.16.4_avm
    steps:
      - name: /root/.cargo to PATH
        run: |
          echo '/root/.cargo/bin/' >> $GITHUB_PATH
          echo '/root/.avm/bin' >> $GITHUB_PATH
          ln -s /root/.avm $HOME/
          ln -s /root/.config/solana $HOME/
      - name: Info on AVM
        run: |
          avm list
          avm use 0.28.0
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Set nightly toolchain
        run: rustup default nightly
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Check solana config
        run: solana config get

      - name: Running tests for project
        run: |
          yarn
          yarn test
