name: "Anchor Test"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/setup-anchor@v1.1
        with: 
          anchor-version: '0.28.0' 
          solana-cli-version: '1.16.6'
          node-version: '18.12.1'

      - run: yarn
      - run: anchor test
